# Site settings
title: Janine & Liam
description: "Janine & Liam"
baseurl: ""
url: "http://janineandliam.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

# Ignore
exclude:
- CNAME
- Gruntfile.js
- README.md
- node_modules
- package.json
